# Generated by Django 4.0.6 on 2022-07-20 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trackApp', '0009_remove_project_manager_project_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='member',
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='%(class)s_projectMember', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='project',
            name='manager',
        ),
        migrations.AddField(
            model_name='project',
            name='manager',
            field=models.ManyToManyField(related_name='%(class)s_projectManager', to=settings.AUTH_USER_MODEL),
        ),
    ]
